version: '3'

services:
  postgres:
    image: 'postgres:14.0-alpine'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_DB=superBookDB'